[package]
name = "Euler solution 0007"
version = "1.0.0"
authors = ["Zachary Bush <zabu.other@gmail.com" ]

[dependencies.libeuler]
path = "../libeuler"

[dependencies]
num = "*"

[[bin]]
name = "0007"
path = "src/main.rs"
